// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEGmq9RCXVHdY3KJppu73q6_A0bz2KAiI',
    appId: '1:1055860128585:web:08ae8bc569150303547898',
    messagingSenderId: '1055860128585',
    projectId: 'sabir-tailors',
    authDomain: 'sabir-tailors.firebaseapp.com',
    databaseURL: 'https://sabir-tailors-default-rtdb.firebaseio.com',
    storageBucket: 'sabir-tailors.appspot.com',
    measurementId: 'G-V6KXPQ7S88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZF66rmOWebOww5baliGY72kpDeQvQ5F8',
    appId: '1:1055860128585:android:7c0e3d72002e88de547898',
    messagingSenderId: '1055860128585',
    projectId: 'sabir-tailors',
    databaseURL: 'https://sabir-tailors-default-rtdb.firebaseio.com',
    storageBucket: 'sabir-tailors.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYOt5Q72duhsWyiI-o8P7mx_QO0n01fr0',
    appId: '1:1055860128585:ios:6fb15e474690f3c8547898',
    messagingSenderId: '1055860128585',
    projectId: 'sabir-tailors',
    databaseURL: 'https://sabir-tailors-default-rtdb.firebaseio.com',
    storageBucket: 'sabir-tailors.appspot.com',
    iosBundleId: 'com.example.sabirTailors',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYOt5Q72duhsWyiI-o8P7mx_QO0n01fr0',
    appId: '1:1055860128585:ios:6fb15e474690f3c8547898',
    messagingSenderId: '1055860128585',
    projectId: 'sabir-tailors',
    databaseURL: 'https://sabir-tailors-default-rtdb.firebaseio.com',
    storageBucket: 'sabir-tailors.appspot.com',
    iosBundleId: 'com.example.sabirTailors',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEGmq9RCXVHdY3KJppu73q6_A0bz2KAiI',
    appId: '1:1055860128585:web:3ff087ce47b59dcf547898',
    messagingSenderId: '1055860128585',
    projectId: 'sabir-tailors',
    authDomain: 'sabir-tailors.firebaseapp.com',
    databaseURL: 'https://sabir-tailors-default-rtdb.firebaseio.com',
    storageBucket: 'sabir-tailors.appspot.com',
    measurementId: 'G-CFQTDPEESY',
  );

}